// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

// Purpose: This is the Command Center for the Prisma engine (introduced in version 7).
// Role: It tells the Prisma CLI where to find your schema.prisma and where to save migrations. It also stores settings for how Prisma should connect to your database (like the DATABASE_URL). It basically manages the "environment" for Prisma.